import { TFile } from 'obsidian';

import { pause } from '../api/client';
import { GetNotePluginHost } from '../host';
import { GetNoteChannelSettings, UID_FIELD } from '../types';
import { extractWritableBody, readFrontmatterUid } from './render';

/** `note/update` accepts a tag list; the channel caps it so a runaway file cannot flood the API. */
const MAX_TAGS = 20;
/** `note/save` answers with a task for asynchronous note types; the task is polled. */
const TASK_POLL_INTERVAL_MS = 3000;
const TASK_POLL_ATTEMPTS = 20;

/**
 * Matches the `uid` value on its own frontmatter line. `[^\r\n]*` keeps the line
 * ending out of the match, so replacing the match leaves the file byte-identical
 * apart from the value itself.
 */
const UID_LINE_PATTERN = new RegExp(`^([ \\t]*)${UID_FIELD}[ \\t]*:[^\\r\\n]*`, 'm');
const FRONTMATTER_PATTERN = /^(---\r?\n)([\s\S]*?)(\r?\n---)/;

/** `folder` empty means "every file"; otherwise the file must live below it. */
function isInsideFolder(filePath: string, folder: string): boolean {
	const prefix = folder.replace(/^\/+|\/+$/g, '');
	if (prefix.length === 0) return true;
	return filePath.startsWith(`${prefix}/`);
}

/** Index values are `"<vaultPath>|<updatedAt>"`; entries written before the marker existed hold a bare path. */
function readIndexPath(marker: string): string {
	const separator = marker.lastIndexOf('|');
	return separator < 0 ? marker : marker.slice(0, separator);
}

/** Reverse index lookup: the note id behind a vault path, or '' when it was never pulled. */
function findNoteIdByPath(settings: GetNoteChannelSettings, filePath: string): string {
	for (const [noteId, marker] of Object.entries(settings.index)) {
		if (readIndexPath(marker) === filePath) return noteId;
	}
	return '';
}

/** Snowflake ids must stay strings: YAML reads an unquoted digit run as a number and rounds it. */
function uidScalar(noteId: string): string {
	return /^\d+$/.test(noteId) ? `"${noteId}"` : noteId;
}

/**
 * Inserts or refreshes the `uid` frontmatter field and returns the new markdown.
 * Everything else — frontmatter order, spacing, body, trailing newline — is
 * copied verbatim; only the value token of the `uid` line is rewritten.
 */
function withUidFrontmatter(markdown: string, noteId: string): string {
	const line = `${UID_FIELD}: ${uidScalar(noteId)}`;
	const block = FRONTMATTER_PATTERN.exec(markdown);
	if (!block) return `---\n${line}\n---\n${markdown}`;
	const [whole, open, body, close] = block;
	const patchedBody = UID_LINE_PATTERN.test(body) ? body.replace(UID_LINE_PATTERN, `$1${line}`) : `${line}\n${body}`;
	return open + patchedBody + close + markdown.slice(whole.length);
}

/**
 * Local -> cloud direction.
 *
 * Only the writable region travels: everything below `CONTENT_END` (transcript,
 * timeline, attachment index, ...) is derived from the cloud copy and is
 * regenerated by the next pull, so pushing it back would be pointless churn.
 */
export class PushEngine {
	private readonly host: GetNotePluginHost;

	constructor(host: GetNotePluginHost) {
		this.host = host;
	}

	/**
	 * Creates a cloud note from a local file, or updates it when `uid` frontmatter exists.
	 * Refuses files the settings exclude, and files without a writable body.
	 */
	async pushFile(file: TFile): Promise<{ noteId: string; created: boolean; pending: boolean }> {
		const settings = this.host.getNoteSettings;
		if (!settings.pushEnabled) throw new Error('推送未启用：请在插件设置中开启「启用推送」。');
		const folder = settings.pushFolder.trim();
		if (folder.length > 0 && !isInsideFolder(file.path, folder)) {
			throw new Error(`文件不在推送文件夹「${folder}」内。`);
		}
		const markdown = await this.host.app.vault.read(file);
		if (markdown.trim().length === 0) throw new Error(`「${file.basename}」为空文件，未推送。`);
		const body = extractWritableBody(markdown);
		if (body.trim().length === 0) throw new Error(`「${file.basename}」正文为空，未推送。`);
		const tags = this.readTags(file);
		const uid = readFrontmatterUid(markdown);

		if (uid.length > 0) {
			// `updateNote` replaces the tag list, so an empty frontmatter list is
			// sent as "absent" to leave the cloud tags alone.
			await this.host.endpoints.updateNote({
				noteId: uid,
				title: file.basename,
				content: body,
				tags: tags.length > 0 ? tags : undefined,
			});
			return { noteId: uid, created: false, pending: false };
		}

		const saved = await this.host.endpoints.saveNote({
			noteType: 'plain_text',
			title: file.basename,
			content: body,
			tags: tags.length > 0 ? tags : undefined,
		});
		let noteId = saved.noteId;
		if (saved.pending) noteId = await this.awaitTask(saved.taskIds[0], file);
		await this.writeUid(file, noteId);
		return { noteId, created: true, pending: saved.pending };
	}

	/** Shares the cloud note behind a local file and returns its public url. */
	async shareFile(file: TFile): Promise<string> {
		const markdown = await this.host.app.vault.read(file);
		let noteId = readFrontmatterUid(markdown);
		if (noteId.length === 0) noteId = findNoteIdByPath(this.host.getNoteSettings, file.path);
		if (noteId.length === 0) throw new Error(`「${file.basename}」尚未关联云端笔记，请先执行推送。`);
		return this.host.endpoints.shareNote(noteId, false);
	}

	/**
	 * `link`/`img_text` saves answer with a task instead of a note id; poll until
	 * the note id resolves so the local file can be linked to it.
	 */
	private async awaitTask(taskId: string | undefined, file: TFile): Promise<string> {
		if (!taskId || taskId.length === 0) throw new Error(`「${file.basename}」保存任务缺少 ID，无法确认结果。`);
		for (let attempt = 0; attempt < TASK_POLL_ATTEMPTS; attempt++) {
			await pause(TASK_POLL_INTERVAL_MS);
			const progress = await this.host.endpoints.taskProgress(taskId);
			if (progress.status === 'failed') throw new Error(`「${file.basename}」云端处理失败。`);
			if (progress.noteId.length > 0) return progress.noteId;
		}
		throw new Error(`「${file.basename}」云端处理超时，请稍后在得到大脑中确认。`);
	}

	/** Re-reads before patching so an edit made during the API call is not lost. */
	private async writeUid(file: TFile, noteId: string): Promise<void> {
		const current = await this.host.app.vault.read(file);
		const patched = withUidFrontmatter(current, noteId);
		if (patched !== current) await this.host.app.vault.modify(file, patched);
	}

	/** Frontmatter `tags`, strings only, deduplicated and capped; `metadataCache` parses the YAML. */
	private readTags(file: TFile): string[] {
		const raw: unknown = this.host.app.metadataCache.getFileCache?.(file)?.frontmatter?.tags;
		const source = Array.isArray(raw) ? raw : typeof raw === 'string' ? raw.split(/[,;]/) : [];
		const tags: string[] = [];
		for (const entry of source) {
			if (typeof entry !== 'string') continue;
			const tag = entry.trim().replace(/^#+/, '');
			if (tag.length === 0 || tags.includes(tag)) continue;
			tags.push(tag);
			if (tags.length >= MAX_TAGS) break;
		}
		return tags;
	}
}
